Add specs
bitboxer/gem-web pull request #6
Opened 2019-03-18 20:44 UTC by MatheusRich

I've added some specs to fill flow that weren't tested. Now the code coverage is 100% :smile:

Tell me if there's something to change.

![image](https://user-images.githubusercontent.com/20938712/54562286-77367580-49a5-11e9-9a1f-2da2bb0a1753.png)

2019-03-18 20:49 UTC, bitboxer requested changes
Looks good, but there is one thing you might need to change.

2019-03-18 20:49 UTC, bitboxer commented on lib/gem/web/executor.rb
> +        rescue VCR::Errors::UnhandledHTTPRequestError => ex
This looks weird to me at a first glance. VCR is only a dev dependency for the tests and it looks like it leaks through here to "production" code. This should not be here.

2019-03-18 20:49 UTC, MatheusRich commented on lib/gem/web/executor.rb
> +        rescue VCR::Errors::UnhandledHTTPRequestError => ex
I had to change this because this was the exception raised with an unexisting gem.

2019-03-18 20:50 UTC, MatheusRich commented on spec/gem/web/executor_spec.rb
> +      Gem::Web::Executor.new.open_page("rails", {github: true})
I thought this would be a bit clearer.

2019-03-18 20:53 UTC, MatheusRich commented on lib/gem/web/executor.rb
> +        rescue VCR::Errors::UnhandledHTTPRequestError => ex
As I mentioned bellow, this was the exception raised when I tested with an unexisting gem. Any thoughts on how to get an `OpenURI::HTTPError`?

2019-03-18 21:08 UTC, bitboxer commented on lib/gem/web/executor.rb
> +        rescue VCR::Errors::UnhandledHTTPRequestError => ex
You might need to disable VCR for a test. You will get this without VCR and a gem that doesn't exist when I remember correctly.

2019-03-19 02:19 UTC, MatheusRich commented on lib/gem/web/executor.rb
> +        rescue VCR::Errors::UnhandledHTTPRequestError => ex
I think it's okay now. What do you think?

2019-03-19 08:18 UTC, bitboxer approved these changes

2019-03-19 08:18 UTC, bitboxer commented
If you remove the WIP and signal that this is done for you, I will merge this asap.

2019-03-19 10:55 UTC, MatheusRich commented
You can merge it now.

2019-03-19 10:57 UTC, merged

2019-03-19 10:57 UTC, bitboxer commented
Awesome. Thank you!

2019-03-19 10:58 UTC, MatheusRich commented
Is there anything more to do? :smile:

2019-03-19 11:02 UTC, bitboxer commented
Hm...not that I know of.